travis:
  secure:
    BINSTAR_TOKEN: H84g5YQPYQ9z9dYVFgexXz3/ZkyRd9JG6VYrk83XIsOeibYPAcJp+THzGK0ObHclP+xnHkN/OLMZWZmc2Y8daUK8cv3tgd6Exrm8jda5NblTEO9MFoSSigS3Y9UmXN0uT/w1wPxGLjVyQpzWJV14NrxquJz7T+BvYhlZqQu/ce9Djh/TQrPm8XvQl+QtIvqpY0JgMuDJTQxKbw6Ua5KMu7MDITiYSJVHU/58TrVJC8NKCzjpITvDL5IQyjqBp08NIkTZUfdrqfMZqXfizG3rl34680KfC7ftg7a801f+wJuYkwP1QFixoIw7sWvze+OSq88dHuWeJOu/gLBL++mn5OlQJ3bC+UEwHjWzn+C0mrqgF9EPAj+8ivngjwLjbDL9+Y1Z+6k8da7LTZPoRwq5BQYYAk7kCntdt6ItLV/3OPygcAce6bSNbEtvqRV4+L8RHIjYXEE50gbhP2jVHmLePQ+4T+uOwt4DBRPSJoB/gmIkriPkXHv7FooTaFdEBR27w//+L5pRSTyRUomVuKRjDOuz95gJASU1njIi2GZND68gI6jiFzgpylYsf/LiIs8fTbNXPjyQE8p23aXW9rHVxS5dSmTc0f/StG0T7aPm8cLw5oKxDQUk/nMqfaV/DRPWB84ap8zbfWlB8i9lDv/4WqJ1Y1+po7xevnWIHfIQkwo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
